tjsduq0423/WhereIsMyHome

backend/build.gradle
스웨거 api 문서화 의존성 추가 후 문서화 확인 테스트 완료
api문서 주소: http://localhost:8080/swagger-ui/index.html#/
=> Feature/swagger 스웨거 의존성 추가

backend/build.gradle, backend/src/main/java/com/whereismyhome/board/controller/BoardController.java, backend/src/main/java/com/whereismyhome/board/dto/BoardListResponseDto.java, backend/src/main/java/com/whereismyhome/board/dto/BoardPostDto.java, backend/src/main/java/com/whereismyhome/board/entity/Board.java, backend/src/main/java/com/whereismyhome/board/mapper/BoardMapper.java, backend/src/main/java/com/whereismyhome/board/repository/BoardRepository.java, backend/src/main/java/com/whereismyhome/board/service/BoardService.java, backend/src/main/java/com/whereismyhome/jwt/JwtAuthenticationFilter.java, backend/src/main/java/com/whereismyhome/jwt/JwtProvider.java, backend/src/main/java/com/whereismyhome/member/entity/Member.java
- 게시글 등록
---
- 본인이 작성한 게시글 조회
---
- 게시글 삭제
---
- 객체 매핑 관련 라이브러리 추가
=> Feature/board 게시글 추가, 삭제, 조회

backend/src/main/java/com/whereismyhome/notice/controller/NoticeController.java, backend/src/main/java/com/whereismyhome/notice/dto/NoticePostDto.java, backend/src/main/java/com/whereismyhome/notice/dto/NoticePutDto.java, backend/src/main/java/com/whereismyhome/notice/dto/NoticeResponseDto.java, backend/src/main/java/com/whereismyhome/notice/entity/Notice.java, backend/src/main/java/com/whereismyhome/notice/mapper/NoticeMapper.java, backend/src/main/java/com/whereismyhome/notice/repository/NoticeRepository.java, backend/src/main/java/com/whereismyhome/notice/service/NoticeService.java
- 공지사항 등록
- 공지사항 수정 (수정 시 공지 수정시간 반영)
- 공지사항 삭제
- 공지사항 전체 조회
=> Feature/notice back 공지사항 CRUD 구성

backend/src/main/java/com/whereismyhome/bookmark/controller/BookMarkController.java, backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkDto.java, backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkResponseDto.java, backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkServiceDto.java, backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkUpdateDto.java, backend/src/main/java/com/whereismyhome/bookmark/entity/BookMark.java, backend/src/main/java/com/whereismyhome/bookmark/mapper/BookMarkMapper.java, backend/src/main/java/com/whereismyhome/bookmark/repository/BookMarkRepository.java, backend/src/main/java/com/whereismyhome/bookmark/service/BookMarkService.java, backend/src/main/java/com/whereismyhome/houseinfo/entity/HouseInfo.java
- 북마크 추가
- 북마크 추가 기능 테스트 후 db 확인
- 북마크 삭제
1. native 쿼리를 사용하여 회원 id와 apt code에 맞는 데이터 삭제
- 북마크 삭제 기능 테스트 후 db 확인
- 쿼리 메서들 사용하여 db에서 member_id에 해당되는 데이터만 조회
resolved: #9
=> 9 feature bookmark 북마크 기능 추가

backend/src/main/java/com/whereismyhome/bus/entity/Bus.java, backend/src/main/java/com/whereismyhome/cctv/entity/Cctv.java, backend/src/main/java/com/whereismyhome/dongcode/entity/DongCode.java, backend/src/main/java/com/whereismyhome/hospital/Housedeal.java, backend/src/main/java/com/whereismyhome/hospital/entity/Hospital.java, backend/src/main/java/com/whereismyhome/houseinfo/entity/HouseInfo.java, backend/src/main/java/com/whereismyhome/houseinfo/shool/entity/School.java, backend/src/main/java/com/whereismyhome/subway/entity/Subway.java
=> 13 feature/entity

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/assets/data/homeChart.js, FrontEnd/src/assets/styles/main.scss, FrontEnd/src/assets/styles/test.scss, FrontEnd/src/components/AppBarChart.vue, FrontEnd/src/components/AppContent.vue, FrontEnd/src/components/AppFooter.vue, FrontEnd/src/components/AppLineChart.vue, FrontEnd/src/components/AppNav.vue, FrontEnd/src/views/HomeView.vue, FrontEnd/src/views/NotFoundView.vue, FrontEnd/src/views/auth/FindPasswordView.vue, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/auth/SignUpView.vue, FrontEnd/src/views/board/NoticeCreateView.vue, FrontEnd/src/views/board/NoticeDetailView.vue, FrontEnd/src/views/board/NoticeEditView.vue, FrontEnd/src/views/board/NoticeView.vue, FrontEnd/src/views/board/QnACreateView.vue, FrontEnd/src/views/board/QnADetailView.vue, FrontEnd/src/views/board/QnAEditView.vue, FrontEnd/src/views/board/QnAView.vue, FrontEnd/src/views/main/AptInfoView.vue, FrontEnd/src/views/main/MyPageView.vue, FrontEnd/vite.config.js
=> 24 홈 화면 chartjs 추가

FrontEnd/src/api/aptInfo.js, FrontEnd/src/api/board.js, FrontEnd/src/api/http.js, FrontEnd/src/components/AppBoardForm.vue, FrontEnd/src/components/AppContent.vue, FrontEnd/src/views/auth/FindPasswordView.vue, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/auth/SignUpView.vue, FrontEnd/src/views/board/NoticeDetailView.vue, FrontEnd/src/views/board/NoticeView.vue, FrontEnd/src/views/board/QnADetailView.vue, FrontEnd/src/views/board/QnAView.vue, FrontEnd/src/views/main/AptInfoView.vue
Axios 의존성 추가
Axios 공통 모듈 생성
기능 별 directory 생성 및 api 생성.
intercepter 오류 처리
apt info card 상단 마진
---- intercepter 오류시 알람 부분. check.
기능별 directorory -> .js 모듈 => import 해서 사용.
=> 25 axios 라이브러리 등록 및 모듈화 적용

backend/src/main/java/com/whereismyhome/board/controller/BoardController.java, backend/src/main/java/com/whereismyhome/config/AppConfig.java, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
=> 34 cors 설정

FrontEnd/.eslintrc.cjs, FrontEnd/src/api/aptInfo.js, FrontEnd/src/api/board.js, FrontEnd/src/api/http.js, FrontEnd/src/assets/data/aptData.js, FrontEnd/src/assets/data/homeChart.js, FrontEnd/src/components/AppBarChart.vue, FrontEnd/src/components/AppContent.vue, FrontEnd/src/components/AppNav.vue, FrontEnd/src/components/AppSideBar.vue, FrontEnd/src/views/HomeView.vue, FrontEnd/src/views/main/AptInfoView.vue
=> 29 aptinfo 사이드 바 content

backend/.gitignore
=> #40 add: gitignore 추가

FrontEnd/src/api/index.js
=> Delete branch #31

backend/.gitignore
=> #40 update: gitignore 변경

FrontEnd/jsconfig.json, FrontEnd/src/components/AppBoardForm.vue, FrontEnd/src/components/AppNav.vue, FrontEnd/src/components/AppPaginationBar.vue, FrontEnd/src/stores/auth.js, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/board/NoticeCreateView.vue, FrontEnd/src/views/board/NoticeDetailView.vue, FrontEnd/src/views/board/NoticeEditView.vue, FrontEnd/src/views/board/NoticeView.vue, FrontEnd/src/views/board/QnACreateView.vue, FrontEnd/src/views/board/QnADetailView.vue, FrontEnd/src/views/board/QnAEditView.vue, FrontEnd/src/views/board/QnAView.vue, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
-api 연결 DB에 글 CRUD 완료
----------------------------------------------------------------
=> 48 공지 글쓰기 api 등록

backend/src/main/java/com/whereismyhome/board/repository/BoardRepository.java, backend/src/main/java/com/whereismyhome/board/service/BoardService.java, backend/src/main/java/com/whereismyhome/notice/service/NoticeService.java
1. 게시판 수정이 되지 않던 부분 변경
2. 게시판 글 목록 최신순으로 정렬
3. 공지사항 글 목록 최신순으로 정렬
=> 게시판, 공지사항 로직 일부 변경

FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/board/NoticeDetailView.vue, FrontEnd/src/views/board/NoticeEditView.vue, FrontEnd/src/views/board/NoticeView.vue, FrontEnd/src/views/board/QnACreateView.vue, FrontEnd/src/views/board/QnADetailView.vue, FrontEnd/src/views/board/QnAEditView.vue, FrontEnd/src/views/board/QnAView.vue, backend/src/main/java/com/whereismyhome/board/service/BoardService.java
- 알림 Composable code 작성
- 모든 view 에서 일어나는 상호작용에 알림 등록
=> Update feature #49

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/App.vue, FrontEnd/src/components/AppAlert.vue, FrontEnd/src/components/AppContent.vue, FrontEnd/src/components/AppNav.vue, FrontEnd/src/composables/alert.js, FrontEnd/src/main.js, FrontEnd/src/router/index.js, FrontEnd/src/stores/alert.js, FrontEnd/src/stores/auth.js, FrontEnd/src/views/auth/FindPasswordView.vue, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/auth/SignUpView.vue, FrontEnd/src/views/board/NoticeCreateView.vue, FrontEnd/src/views/board/QnACreateView.vue
라우터 네비게이션 가드 설정
- isAdmin , requiresAuth
- router transition 적용
- animate css npm 모듈 install
- 알람, 페이지 라우팅 transtion css 적용
=> 56 라우팅 네비게이션 가드 설정

backend/build.gradle, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java, backend/src/main/java/com/whereismyhome/member/controller/MemberController.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java, backend/src/main/resources/application.yml
- 회원가입 시 이메일 인증 코드 전송 및 response
resloved: #60
=> 60 메일 서비스 구현

FrontEnd/src/components/AppModal.vue, FrontEnd/src/views/auth/FindPasswordView.vue, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/auth/SignUpView.vue
- 이메일 인증, 비밀번호 찾기 ui 모달 생성
closes #58
=> Update feature #62

FrontEnd/src/components/AppCardHeader.vue, FrontEnd/src/components/AppInfinityScroll.vue, FrontEnd/src/views/main/my/MyBookMarkView.vue, FrontEnd/src/views/main/my/MyPageView.vue
=> Update feature #58

FrontEnd/src/views/auth/LoginView.vue, backend/build.gradle, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java, backend/src/main/java/com/whereismyhome/member/controller/MemberController.java, backend/src/main/java/com/whereismyhome/member/mapper/MemberMapper.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java, backend/src/main/java/com/whereismyhome/oauth2/controller/Oauth2Controller.java, backend/src/main/java/com/whereismyhome/oauth2/dto/TokenDto.java, backend/src/main/java/com/whereismyhome/oauth2/service/Oauth2Service.java, backend/src/main/java/com/whereismyhome/role/entity/MemberRole.java, backend/src/main/resources/application.yml
=> 64 oauth20 sns로그인 구현

backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java, backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java, backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java, backend/src/main/java/com/whereismyhome/houseinfo/dto/ChartDataDto.java, backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseResponseDto.java, backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java, backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java, backend/src/main/java/com/whereismyhome/houseinfo/service/HouseInfoService.java
- 많이 느림
- 해당 아파트 평균가격
- 해당 아파트 건설 연도
=> 72 지역별 거래량 조회수 북마크 조회

backend/src/main/java/com/whereismyhome/amenities/repository/CctvRepository.java
=> update: cctv 반환 데이터 제한

backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java, backend/src/main/java/com/whereismyhome/board/service/BoardService.java, backend/src/main/java/com/whereismyhome/exception/ExceptionCode.java, backend/src/main/java/com/whereismyhome/exception/ExceptionController.java, backend/src/main/java/com/whereismyhome/member/controller/MemberController.java, backend/src/main/java/com/whereismyhome/member/entity/Member.java, backend/src/main/java/com/whereismyhome/member/mapper/MemberMapper.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java, backend/src/main/java/com/whereismyhome/notice/service/NoticeService.java
=> 77 비밀번호 찾기 및 비즈니스 로직 예외처리

backend/src/main/java/com/whereismyhome/bookmark/controller/BookMarkController.java, backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkResponseDto.java, backend/src/main/java/com/whereismyhome/bookmark/mapper/BookMarkMapper.java, backend/src/main/java/com/whereismyhome/bookmark/repository/BookMarkRepository.java, backend/src/main/java/com/whereismyhome/bookmark/service/BookMarkService.java, backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
해당 아파트 최소 거래가격, 최대 거래가격 표시
resloved: #81
=> 81 마이페이지 북마크 리스트 정보

backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java, backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java, backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java, backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseResponseDto.java, backend/src/main/java/com/whereismyhome/houseinfo/entity/HouseInfo.java, backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java, backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java
전체 아파트 정보 반환
아파트 정보 테이블에 컬럼 평균 매매가를 넣은 컬럼을 추가하여 조회 진행
카카오 로그인으로 회원가입 진행 후 로그인 시 발생하는 에러 수정
=> 84 전체 아파트 정보 반환

backend/src/main/java/com/whereismyhome/member/controller/MemberController.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java
=>  #89 add: 회원 중복 체크 api 분리

backend/src/main/java/com/whereismyhome/amenities/dto/response/SubwaySearchResponseDto.java, backend/src/main/java/com/whereismyhome/amenities/repository/SubwayRepository.java, backend/src/main/java/com/whereismyhome/bookmark/entity/BookMark.java, backend/src/main/java/com/whereismyhome/dongcode/dto/DonCodeSearchResponseDto.java, backend/src/main/java/com/whereismyhome/dongcode/mapper/DongCodeMapper.java, backend/src/main/java/com/whereismyhome/houseinfo/dto/HouseSearchResponseDto.java, backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java, backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java, backend/src/main/java/com/whereismyhome/search/controller/SearchController.java, backend/src/main/java/com/whereismyhome/search/service/SearchService.java
검색 기능 api
구군 이름 + 해당 구에 속하는 아파트 개수
아파트 이름 + 북마크 개수 조회
지하철 이름 조회
resloved: #91
=> 91 검색 구군 이름 지하철 이름 아파트 이름 api

FrontEnd/src/api/member.js, FrontEnd/src/components/features/AppModal.vue, FrontEnd/src/views/auth/FindPasswordView.vue, FrontEnd/src/views/auth/SignUpView.vue, backend/src/main/java/com/whereismyhome/member/service/MemberService.java
- 비밀번호 찾기 -> 인증 -> 비밀번호 변경
- 회원가입 -> 인증 -> 회원가입 완료
closes #87
=> Update 회원가입, 비밀번호 변경 인증 #87

backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java, backend/src/main/java/com/whereismyhome/amenities/dto/response/BusResponseDto.java, backend/src/main/java/com/whereismyhome/amenities/dto/response/HospitalResponseDto.java, backend/src/main/java/com/whereismyhome/amenities/dto/response/SchoolResponseDto.java, backend/src/main/java/com/whereismyhome/amenities/dto/response/SubwayResponseDto.java, backend/src/main/java/com/whereismyhome/amenities/mapper/AmenMapper.java, backend/src/main/java/com/whereismyhome/amenities/repository/BusRepository.java, backend/src/main/java/com/whereismyhome/amenities/repository/HospitalRepository.java, backend/src/main/java/com/whereismyhome/amenities/repository/SchoolRepository.java, backend/src/main/java/com/whereismyhome/amenities/repository/SubwayRepository.java, backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java
편의 시설 모든 반환 데이터에 해당
좌표(해당 아파트)부터 편의 시설까지의 거리 반환
resolved: #95
=> 95 사이드바 편의시설 반환 데이터 변경

FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/stores/bookmark.js, FrontEnd/src/stores/markers.js, FrontEnd/src/views/main/AptInfoView.vue, backend/src/main/java/com/whereismyhome/config/SecurityConfig.java
마커 데이터 필터링 (금액 , 건설 년도)
기존의 구조를 탈피하고 전체를 가지고 필터링 visible하는 함수를 구현해야함.
배열에 [markerInfo, mapMarkerObject]를 담아 놓고 filtering 변수를 감시하면서 변할 때마다. 함수를 실행 . 금액 필터에는 debounce 적용
closes #76
=> Update #76 마커 필터링 구현

FrontEnd/src/api/bookmark.js, FrontEnd/src/api/member.js, FrontEnd/src/components/features/AptInfoSideBar.vue, FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/stores/bookmark.js, FrontEnd/src/views/auth/SignUpView.vue
회원가입 이메일 중복검사 로직 작성
북마크 버튼 api 제어
closes #76
=> Update #99 중복검사, 북마크

FrontEnd/src/stores/auth.js, backend/src/main/java/com/whereismyhome/member/controller/MemberController.java, backend/src/main/java/com/whereismyhome/member/entity/Member.java, backend/src/main/java/com/whereismyhome/member/service/MemberService.java, backend/src/main/java/com/whereismyhome/oauth2/controller/Oauth2Controller.java
회원 가입 및 삭제 시 영속성 전이로 인한 role이 같이 저장되고 같이 삭제가 됨
카카오 로그인 정상 작동되게 수정
=> #98 add: 회원 삭제 및 cascade 적용

backend/src/main/java/com/whereismyhome/amenities/controller/AmenController.java, backend/src/main/java/com/whereismyhome/amenities/service/AmenService.java, backend/src/main/java/com/whereismyhome/houseinfo/mapper/HouseInfoMapper.java, backend/src/main/java/com/whereismyhome/houseinfo/repository/HouseInfoRepository.java
=> #103 update: 지도 중심 좌표 기준으로 아파트 정보 반환

FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/components/layouts/AppNav.vue, FrontEnd/src/stores/homeChart.js, FrontEnd/src/views/HomeView.vue, FrontEnd/src/views/auth/SignUpView.vue, FrontEnd/src/views/board/NoticeCreateView.vue, FrontEnd/src/views/board/QnACreateView.vue, FrontEnd/src/views/board/QnAView.vue, FrontEnd/src/views/main/my/MyBookMarkView.vue, FrontEnd/src/views/main/my/MyPageView.vue, FrontEnd/src/views/main/my/MyQnAView.vue
=> 101 마이페이지 UI 완성

backend/src/main/java/com/whereismyhome/amenities/mapper/AmenMapper.java, backend/src/main/java/com/whereismyhome/dongcode/dto/GuGunAvgMountDto.java, backend/src/main/java/com/whereismyhome/dongcode/mapper/DongCodeMapper.java, backend/src/main/java/com/whereismyhome/dongcode/repository/DongCodeRepository.java, backend/src/main/java/com/whereismyhome/dongcode/service/DongCodeService.java, backend/src/main/java/com/whereismyhome/houseinfo/controller/InfoController.java
지역구별 평균 매매가 api 생성
resolved: #103
=> #103 add: 지역구별 평균 매매가 api 생성

FrontEnd/src/api/amen.js, FrontEnd/src/api/index.js, FrontEnd/src/api/search.js, FrontEnd/src/components/features/AptInfoSideBar.vue, FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/stores/markers.js, FrontEnd/src/stores/search.js, FrontEnd/src/views/HomeView.vue, FrontEnd/src/views/main/AptInfoView.vue
=> 106 검색 바 아파트 조회 수정

FrontEnd/src/stores/homeChart.js
=> add: 차트데이터 비중 변경

FrontEnd/package-lock.json, FrontEnd/package.json, FrontEnd/src/api/amen.js, FrontEnd/src/api/info.js, FrontEnd/src/components/features/AptInfoSideBar.vue, FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/stores/aptInfo.js, FrontEnd/src/stores/sideBar.js, FrontEnd/src/views/auth/LoginView.vue, FrontEnd/src/views/board/QnADetailView.vue, FrontEnd/src/views/main/AptInfoView.vue, FrontEnd/src/views/main/my/MyBookMarkView.vue, FrontEnd/src/views/main/my/MyPageView.vue, FrontEnd/src/views/main/my/MyQnAView.vue
Update #109 사이드,게시판 완료
조회수 증가 로직 추가
사이드바 편의시설 거리 tab api 데이터 채우기
게시판 = qna 답변 공간 생성
사이드바 뉴스 탭 html 파싱 좀더
close #109
=> 109 사이드바 게시판 수정

FrontEnd/src/api/info.js, FrontEnd/src/components/features/AptInfoSideBar.vue, FrontEnd/src/components/features/MyAptInfoSideBar.vue, FrontEnd/src/components/kakao/KaKaoMap.vue, FrontEnd/src/components/kakao/MyKaKaoMap.vue, FrontEnd/src/plugins/kakaoMaps.js, FrontEnd/src/stores/bookmark.js, FrontEnd/src/stores/markers.js, FrontEnd/src/views/main/AptInfoView.vue, FrontEnd/src/views/main/my/MyBookMarkInMapView.vue, FrontEnd/src/views/main/my/MyBookMarkView.vue, FrontEnd/src/views/main/my/MyQnAView.vue, FrontEnd/vite.config.js
전국 구에 해당하는 평균 매매가와 위치별 커스텀 오버레이 생성=> 해당 오버레이 클릭시 줌
북마크 뷰 페이지 구성.
마이 북마크 뷰 페이지 구성
해당 마이 북마크 뷰 페이지에 사이드 바 구성.
마이 북마크 뷰 페이지 에서 마커 생성.
해당 마커 사이드바 도 추가.
=> 112 구별 평균 매매가 오버레이 유저 북마크 지도 생성

backend/src/main/java/com/whereismyhome/bookmark/dto/BookMarkResponseDto.java, backend/src/main/java/com/whereismyhome/bookmark/mapper/BookMarkMapper.java, backend/src/main/java/com/whereismyhome/bookmark/repository/BookMarkRepository.java
=> add: 북마크 조회 반환 데이터 수정

FrontEnd/src/components/features/AptInfoSideBar.vue, FrontEnd/src/components/features/MyAptInfoSideBar.vue, FrontEnd/src/components/kakao/MyKaKaoMap.vue, FrontEnd/src/stores/homeChart.js
북마크 리스트 관련 맵 기능 점검
스타일 수정
closes #114
=> Update 구별 평균 매매가 오버레이, 유저 북마크 지도 생성 #114
